### ISSUE TITLE
Incorrect handling of URL with parentheses in the title text

### ISSUE THREAD

**Issue by tgaul** [laptobbe/TSMarkdownParser#12]
I found that when Markdown contains something like this:
   ` [Something something (something)](http://someurl.com)`

The processing code finds the first open paren rather than the last one. A simple fix for this I made in my copy was to change line 195 of TSMarkdownParser.m to use `NSBackwardsSearch` when doing the search for the open parenthesis character.

**Comment by postmechanical** [comment]
Ditto. Just ran into this issue as well.
