### ISSUE TITLE
feature request add remote url to images

### ISSUE THREAD

**Issue by sdupuis1** [laptobbe/TSMarkdownParser#16]
Here is the code:
 if(image == nil)
        {
            NSURL *url = [NSURL URLWithString:imagePath];
            NSData *imageData = [NSData dataWithContentsOfURL:url];
            image = [UIImage imageWithData:imageData];
        }

add the above code in the addImageParsingWithImageFormattingBlock after
 UIImage *image = [UIImage imageNamed:imagePath];

Basically this checks for the remote url path if the existing path is not a local path.

**Comment by laptobbe** [comment]
I like the feature but I have a different take on it. What do you think about having the block for the image parsing returning the image? So what I am getting at is let the user transform a image name to a image. That way we don't have to support all the ways you could get the image data.

**Comment by sdupuis1** [comment]
Not 100% sure what you mean, you want to return the imagePath? not the image.Not sure how you get an uiimage with a remote url without trying to retrieve that data with the imagePath(url). 
just need url capability,so i think as is is good enough. currently if it fails, it will just substitute the image name anyways.

 but on a different note, would be more interested in returning the image attachment(NSTextAttachment). The reason is formatting. once an image is retrieved typically it needs to be resized(is it a retina device or not). I have had gobs of problems with weird attributed text having images scrolling off the screen because it uses the actual image size. Some post processing on the image size typically needs to be done at some point. 


     On Thursday, April 23, 2015 2:11 AM, Tobias Sundstrand <notifications@github.com> wrote:
   

 I like the feature but I have a different take on it. What do you think about having the block for the image parsing returning the image? So what I am getting at is let the user transform a image name to a image. That way we don't have to support all the ways you could get the image data.—

**Comment by sdupuis1** [comment]
Also,I have added a custom tag -> <- for entering and added a line spacing feature, but didn't push to repo as these features are outside the spec and would be considered extensions. Did you want me to add them to the package?P.S. love the capability of adding custom tags.
I may have to add escaping i.e \ character. 


     On Thursday, April 23, 2015 9:21 AM, Serge Dupuis <sdupuis1_ca@yahoo.ca> wrote:
   

 Not 100% sure what you mean, you want to return the imagePath? not the image.Not sure how you get an uiimage with a remote url without trying to retrieve that data with the imagePath(url). 
just need url capability,so i think as is is good enough. currently if it fails, it will just substitute the image name anyways.

 but on a different note, would be more interested in returning the image attachment(NSTextAttachment). The reason is formatting. once an image is retrieved typically it needs to be resized(is it a retina device or not). I have had gobs of problems with weird attributed text having images scrolling off the screen because it uses the actual image size. Some post processing on the image size typically needs to be done at some point. 


     On Thursday, April 23, 2015 2:11 AM, Tobias Sundstrand <notifications@github.com> wrote:
   

 I like the feature but I have a different take on it. What do you think about having the block for the image parsing returning the image? So what I am getting at is let the user transform a image name to a image. That way we don't have to support all the ways you could get the image data.—

**Comment by Coeur** [comment]
@sdupuis1, please give your thoughts on new method `- (void)addImageParsingWithLinkFormattingBlock:(TSMarkdownParserLinkFormattingBlock)formattingBlock;` from version 2.1.0.
