### ISSUE TITLE
Feature request: support for an escaping sequence

### ISSUE THREAD

**Issue by Coeur** [laptobbe/TSMarkdownParser#20]
Thank you for bringing customised Markdown to iOS.

Can you also add support to partially disable Markdown interpretation somehow? Suggested way of doing it would be by using an escape sequence, like '\x' (C-like), '&x;' (xml-like) or '%x' (url-like). I personally recommend the first option, using a backslash, as we do not want to conflict with HTML support.

I will quote the example from http://genius.com/3057216 : "Type M\\\*A\\\*S\\\*H to get M\*A\*S\*H".

To make the regexp simple, suggested behaviour would just be:
* backslash + any character = character without markdown interpretation

**Comment by laptobbe** [comment]
This sounds really useful! 

I will look into this when I have some time over. My spontaneous thought was to add a 'not' condition where we check for special characters. This would mean updating every regex though. 

An alternate way would be to parse the escaped characters first and replace them with a placeholders not containing the special character and then after all the parsing is done replace the placeholders with the special characters. 

Do you have any other suggestions? Would love some input on this.

**Comment by Coeur** [comment]
Well, I'm not an expert at lexicographic or grammar parsing.

There are multiple possible escaping mechanisms we could find:
* `\x` is Shell or C style
* `\uxxxx` is Unicode style
* `&xx;` is XML style
* `%xx` is URL style
* a Base64 style one can be imagined
* ...

But my believe is that the C-style one is the one that fits Markdown best, as it is the only one that *doesn't change the encoding*, and thus keeps everything human-readable. In all cases, we are aware it should be an optional feature.

==Option A: updating all regex==
Actually, with your first proposal, we would keep two regex for everything: one with escaping support for `\x`, and one without. We need to also let developers the ability to define custom rules which are either double-regex, single-regex with escaping support only, or single-regex with no-escaping support only. 
CON:
* should support 2 regex for each defaultParser feature
* might be confusing for defining custom Markdown rules

== Option B: defining a placeholder==
We would be attempting to replace an escaping sequence with a different one, to keep compatibility with current regex. Well, the trick is to find a placeholder which:
a) would be unaffected by existing regex. For that, placeholder should have the opposite characteristic of our escaping sequence: it *should* change the encoding!
b) would be always escaped itself! Let me explain on that...

Example of a failure :
a) each time we see '\x' we replace it with '&xxxx;' (XML equivalent).
b) we parse the markdown
c) each time we see '&xxxx;' we replace it back to '\x'
=> if original string had a '&yyyy;', it would become '\y' in the end. Which means we accidentally altered something that shouldn't be. Bad result.

Example of a success :
a) each time we see '\x' we replace it with '\uXXXX' (unicode equivalent).
b) we parse the markdown
c) each time we see '\uXXXX', we replace it with '\x'
=> we always preserve original string, because our placeholder syntax is luckily *itself* escaped!

==Preference==
Well, to keep things simple I would go with the placeholder solution. Specifically the placeholder with a Unicode syntax of `\uXXXX` (four hexadecimal characters, like in the JSON specifications), as it is the only one safely compatible with backslash escaping.

**Comment by laptobbe** [comment]
## Option A:

I don't like the idea of supporting two different sets of regexes. This will get confusing when you add your own rules as you say, it will also be cumbersome when adding new parsing rules to the defaultParser. I also agree that we should use the C-style escaping. You state very clearly that we should keep it as an optional feature. I am thinking that it would be a lot cleaner to let this be the default behavior. Is there any case where this would break existing parsing?

## Option B:

Really like the idea of UNIX placeholder. This option would actually mean adding quite a few parsing rules. Two for each special character (if we can't combine all the special chars in one regex somehow). But it would be a lot cleaner to implement this as an optional feature, since it would not interfere with the existing regexes.

## Conclusion

So I think if we want it as a optional feature we should use Option B, but if we want it as default behavior we should choose option A.

**Comment by Coeur** [comment]
You mean "unicode" placeholder.

We don't need 2 parsing rules per character: we can do it commonly with something like:
* one parsing rule to match all C escape `\\(.)`
* one parsing rule to match all Unicode escape `\\u([0-9a-z]{4})`

The cases where parsing would be broken would be the one where someone already implemented custom markdown where backslash has a meaning.

**Comment by Coeur** [comment]
https://github.com/laptobbe/TSMarkdownParser/pull/21

**Comment by Coeur** [comment]
I've added the feature to branch 2.0.
