### ISSUE TITLE
In Simulator the markdown parser has a max character limit

### ISSUE THREAD

**Issue by danmademe** [laptobbe/TSMarkdownParser#28]
Using swift

let markdownParser = TSMarkdownParser.standardParser()
markdownParser.attributedStringFromMarkdown(markdownString)

if the markdownString is too long, in simulator it doesn't parse the markdown... this isn't critical but I'm wondering if this is a arch issue

**Comment by danmademe** [comment]
for more information heres the full class i have made, I have extended NSAttributedString to include a markdown parsing function

```import TSMarkdownParser

extension NSAttributedString {
    
    class func parseMarkdownToAttributedString(markdownString: String) -> NSAttributedString {
        
        let tsMarkdown           = TSMarkdownParser.standardParser()
        tsMarkdown.paragraphFont = UIFont(name: PREFS_FONT_REGULAR, size: 15.0)
        tsMarkdown.h1Font        = UIFont(name: PREFS_FONT_MEDIUM, size: 21.0)
        tsMarkdown.h2Font        = UIFont(name: PREFS_FONT_MEDIUM, size: 20.0)
        tsMarkdown.h3Font        = UIFont(name: PREFS_FONT_MEDIUM, size: 19.0)
        tsMarkdown.h4Font        = UIFont(name: PREFS_FONT_MEDIUM, size: 18.0)
        tsMarkdown.h5Font        = UIFont(name: PREFS_FONT_MEDIUM, size: 17.0)
        
        tsMarkdown.emphasisFont  = UIFont(name: PREFS_FONT_MEDIUM, size: 15.0)
        tsMarkdown.strongFont    = UIFont(name: PREFS_FONT_MEDIUM, size: 15.0)
        
        return tsMarkdown.attributedStringFromMarkdown(markdownString)
    }
}```

**Comment by Coeur** [comment]
May you specify which simulator/ios/xcode and the approximate length of string?

**Comment by danmademe** [comment]
Sim Versions
8.1, 8.2, 8.3, 9.0, and 9.1

Phones
5, 5s, 6, 6s (also the plusses)

Latest Xcode (7.1.1)

and about 18500characters...

**Comment by Coeur** [comment]
You would be welcome to provide a test case.

**Comment by danmademe** [comment]
i haven't looked at this code for a couple years, and i'm no longer doing iOS dev.. sorry
