### ISSUE TITLE
URLs containing # are invalid

### ISSUE THREAD

**Issue by ldiqual** [laptobbe/TSMarkdownParser#30]
Because of https://github.com/laptobbe/TSMarkdownParser/pull/22, the following code:

```
[link](http://example.com/path#section)
```

Generates the following url:

```
http://example.com/path%23section
```

Which resolves to a different path than `path`, leading to an invalid URL.

Since strings are converted to NSURL behind the hood, maybe it would be better to ensure that a valid URL string is passed -- and potentially show a warning -- instead of automatically alter the URL with unknown consequences.

**Comment by Coeur** [comment]
Good point, will investigate.

**Comment by Coeur** [comment]
Fixed on Master.

**Comment by ldiqual** [comment]
@Coeur Thank you so much for the quick fix! Would you mind pushing 0.19 to the cocoapods trunk? Thank you :)

**Comment by Coeur** [comment]
I do not have the access for this. We will need the @laptobbe to do it.

**Comment by Coeur** [comment]
In the mean time, I think you can write this in your Podfile to get the latest:

    pod 'TSMarkdownParser', :git => 'https://github.com/laptobbe/TSMarkdownParser.git'

**Comment by laptobbe** [comment]
@ldiqual @Coeur I have pushed the new version now. Great work!
