### ISSUE TITLE
Multiple new line characters are ignored

### ISSUE THREAD

**Issue by darrarski** [laptobbe/TSMarkdownParser#32]
This markdown:
```
# Header\nParagraph
```
will generate correct output:
> # Header
> Paragraph

However, when we use `\n\n` instead of `\n`:
```
# Header\n\nParagraph
```
the output will be incorrect:
> # Header Paragraph

I tried looking at source code and propose some fix or workaround, but I am not sure where `TSMarkdownParser` is generating `NSAttributedString` paragraphs from markdown.

**Comment by darrarski** [comment]
As a temporary workaround, I created `NSString` category that removes duplicated new line characters from string:

`NSString+StringByRemovingDuplicatedNewLineCharacters.h`:
```obj-c
#import <Foundation/Foundation.h>
@interface NSString (StringByRemovingDuplicatedNewLineCharacters)
- (NSString *)stringByRemovingDuplicatedNewLineCharacters;
@end
```

`NSString+StringByRemovingDuplicatedNewLineCharacters.m`:
```obj-c
#import "NSString+StringByRemovingDuplicatedNewLineCharacters.h"
@implementation NSString (StringByRemovingDuplicatedNewLineCharacters)
- (NSString *)stringByRemovingDuplicatedNewLineCharacters
{
    NSString *newLineCharacter = @"\n";
    NSString *pattern = [NSString stringWithFormat:@"(%@( ){0,}){2,}", newLineCharacter];
    NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:pattern
                                                                           options:0
                                                                             error:nil];
    NSString *output = [regex stringByReplacingMatchesInString:self
                                                       options:0
                                                         range:NSMakeRange(0, self.length)
                                                  withTemplate:newLineCharacter];
    return output;
}
@end
```

I am using this category to prepare markdown string before passing it to `TSMarkdownParser`.

**Comment by Coeur** [comment]
Hello. Thanks for reporting. I'll look into it today.

**Comment by Coeur** [comment]
I've made this test:

    - (void)testDefaultH1DoubleNextLine {
        NSAttributedString *attributedString = [self.standardParser attributedStringFromMarkdown:@"# Header\n\nParagraph"];
        UIFont *font = [attributedString attribute:NSFontAttributeName atIndex:12 effectiveRange:NULL];
        UIFont *expectedFont = [UIFont systemFontOfSize:12];
        XCTAssertNotNil(font);
        XCTAssertEqualObjects(font, expectedFont);
        XCTAssertEqual(font.pointSize, 12.f);
        XCTAssertEqualObjects(attributedString.string, @"Header\n\nParagraph");
    }

It is successful. So I can't reproduce your issue with unit testing.

**Comment by Coeur** [comment]
I've added a visual Example project with a ViewController on Master branch. And I can't reproduce the issue visually.
![image](http://i.imgur.com/mzB0jnN.png)

**Comment by darrarski** [comment]
You are right. The problem was not connected to `TSMarkdownParser` itself, but it was a result of my configuration. 
I am not using `[TSMarkdownParser standardParser]`, because I want to set up parsing style myself. I made a mistake, and called method `addHeaderParsingWithLevel:formattingBlock:` with level 0 (zero). This caused invalid formatting.
Sorry I bothered you.

**Comment by Coeur** [comment]
No problem.
To tell the truth, I don't use standardParser either. ;)
