### ISSUE TITLE
Carthage Framework Not Working

### ISSUE THREAD

**Issue by jakanter** [laptobbe/TSMarkdownParser#40]
I added TSMarkdownParser to my project using Carthage.  The problem is that I'm getting "**Could not build module TSMarkdownParser**" when I try to include it.  The issue it's giving is that **TSMarkdownParser.h** has **TSBaseParser.h** as an import but the header file is not publicly available.

The error it gives there is "**TSBaseParser.h file not found**"

It assumes that this isn't there because that file is not public.  Might just be a matter of adding that file to the public section of the framework?

**Comment by Coeur** [comment]
Thank you. I will look into in during the week. Or you can submit a pull request.

**Comment by Coeur** [comment]
Should be fixed on master

**Comment by Coeur** [comment]
@jakanter, I've made changes to the frameworks, like adding a module.modulemap. Could you try version 2.0.3 and tell me if Carthage is still working for you?

**Comment by Coeur** [comment]
#49
