### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ldiqual** [laptobbe/TSMarkdownParser#41]
I couldn't find a way to know what's new in 1.0.20 without looking at the diff (which is often verbose and not easy to understand for people who don't know the codebase).

Would you mind adding a changelog or add tag descriptions for each release?

**Comment by Coeur** [comment]
Hello ldiqual and thank you for raising this issue. I will attempt to add a changelog for next commits. But please note those pieces of information:
* branch 1.x is now deprecated
* branch 2.x is now the active branch
* I'm working on a branch 3.x ^_^ but I might release it on a different repository/name if I can't get news from the pod owner.

**Comment by Coeur** [comment]
Also, I wrote at some point a page for migrating from 1.0 to 2.0:
https://github.com/laptobbe/TSMarkdownParser/wiki/1.0-to-2.0-migration

**Comment by Coeur** [comment]
https://github.com/laptobbe/TSMarkdownParser/releases/tag/2.0.2
