### ISSUE TITLE
Double formatting doesn't parse

### ISSUE THREAD

**Issue by SerenadeX** [laptobbe/TSMarkdownParser#42]
If you have both strong and emphasis on the same text, i.e.:

```
"Here is **some text that is both _bold and italic_**"
```

Then it should be able to parse it as follows:

Here is **some text that is both _bold and italic_**

But right now it parses it as

Here is **some text that is both** _bold and italic_

**Comment by Coeur** [comment]
I think we do not support that because bold is one font, italic is another, but we have no rule to combine different fonts. The same issue applies regarding any combination of markdown rules.

**Comment by SerenadeX** [comment]
I think it would be helpful to add in a bold and italic font i.e. `boldItalicFont` property.  That is how I am handling having that font in my app.

**Comment by phatmann** [comment]
:+1:

**Comment by Coeur** [comment]
Note that on OSX, NSFont have traits, so it's easier to combine them.

For iOS and UIFont, if we can't figure out how to combine them, then your suggestion of a `boldItalicFont` property is still complex to implement, as we need to make sure that it will be working for `_a **b** c_` and `**a _b_ c**`, and `***a b c***`. And it should be generic enough to easily allow additional rules with `~~` or `--` as markup to combine with bold and italic as well...

**Comment by SerenadeX** [comment]
Ok we need to list out all of the use cases in the markdown.  The UIFont isn't a problem, we just need to get the font with a bold weight and an italic trait.  As I see these are the following use cases for double formatting:
```markdown
_a **b** c_
*a __b__ c*
**a _b_ c**
__a *b* c__
***a b c***
___a b c___
```

These parse out (according to GitHub markdown) as follows:
_a **b** c_
*a __b__ c*
**a _b_ c**
__a *b* c__
***a b c***
___a b c___

Are there any other cases that I missed?

**Comment by phatmann** [comment]
iOS has UIFontDescriptor so we should be able to combine fonts.

**Comment by phatmann** [comment]
@SerenadeX: looks like you covered all the cases.

**Comment by Coeur** [comment]
@phatmann, thank you, I figured out how to do. But UIFontDescriptor is iOS7+, so I might be using CoreText to support iOS6.

**Comment by Coeur** [comment]
@laptobbe, should we drop support for iOS 6 for TSMarkdownParser 3 for easier combining of rules?

**Comment by laptobbe** [comment]
@Coeur I don't see any problem with dropping iOS 6 and using UIFontDescriptor. If anyone needs iOS 6 support we they could always send a pull request. What do you think?

**Comment by phatmann** [comment]
:+1:

**Comment by Coeur** [comment]
Good.

**Comment by Coeur** [comment]
Double formatting has been implemented in branch 3.x.
I still need:
* to write the tests for it
* discuss the implementation (code review)

**Comment by phatmann** [comment]
Looks good so far. I would drop the iOS 6 support just to make testing easier.

**Comment by Coeur** [comment]
I'll close the issue as resolved, even if not released yet. Hopefully, 3.0 will be here soon.
