### ISSUE TITLE
Escaped periods are not parsed

### ISSUE THREAD

**Issue by SerenadeX** [laptobbe/TSMarkdownParser#43]
If you have a markdown string with an escaped period i.e. `\.` it should parse it to a period:

This
\.

Not
\\.

There may be other issues with other escaped characters.

**Comment by Coeur** [comment]
Hello,
You need to use TSMarkdownParser 2.x to get this feature. I've tried it with the following test and it works:

- (void)testDefaultEscapeParsing {
    NSAttributedString *attributedString = [self.standardParser attributedStringFromMarkdown:@"Hello\\.\n"];
    XCTAssertEqualObjects(attributedString.string, @"Hello.\n");
}

**Comment by SerenadeX** [comment]
Presently 1.0.20 is the only version in CocoaPods.  Could we update the pod to use version 2.x?

**Comment by Coeur** [comment]
Unfortunately I can't. But you can use
pod 'TSMarkdownParser', :git => 'https://github.com/laptobbe/TSMarkdownParser'

**Comment by SerenadeX** [comment]
While that does work it would be nice not to have to do that, what holds us back from updating the version in CocoaPods?

**Comment by Coeur** [comment]
No answer from the owner, @laptobbe.
If it persists for a few more weeks, I plan to release a new pod based on my fork (https://github.com/coeur/TSMarkdownParser) when I finish version 3.

**Comment by laptobbe** [comment]
Sry for being so late to respond. I would be happy to give you access to Cocoa Pods Antoine if you want to manage the releases. As you might have noticed I am preoccupied with other stuff.

24 mars 2016 kl. 11:07 skrev Antoine Cœur <notifications@github.com>:

No answer from the owner, @laptobbe.
If it persists for a few more weeks, I plan to release a new pod based on my fork (https://github.com/coeur/TSMarkdownParser) when I finish version 3.

**Comment by Coeur** [comment]
Hi @laptobbe,

That would be great. I would release version 2.0 on CocoaPods if you allow me. :)

**Comment by laptobbe** [comment]
Hi @Coeur,

I tried to add you but, pod trunk said there was no user with your email. Send me an email at tobias.sundstrand at gmail.com and we will solve that.

**Comment by Coeur** [comment]
Thanks @laptobbe. TSMarkdownParser 2.0.1 is now available.
