### ISSUE TITLE
Links are always blue

### ISSUE THREAD

**Issue by kusmi** [laptobbe/TSMarkdownParser#45]
It does not matter what color I supply to _linkAttributes, the URL stays blue, e.g.

_linkAttributes = @{ NSForegroundColorAttributeName: [UIColor greenColor],
                         NSUnderlineStyleAttributeName: @(NSUnderlineStyleSingle) };

➔ Blue

**Comment by kusmi** [comment]
mhh after further investigation it seems a bug in UILabel - other attributes get applied, just not this text color...

**Comment by Coeur** [comment]
Can you try `@{ (NSString *)kCTForegroundColorAttributeName: [UIColor greenColor], NSUnderlineStyleAttributeName: @(NSUnderlineStyleSingle) }`?

**Comment by kusmi** [comment]
I tried but it does not work. I only tried in Simulator...

**Comment by Coeur** [comment]
A green link: https://upload.wikimedia.org/wikipedia/en/3/39/Wakerlink.jpg

**Comment by Coeur** [comment]
Could be a similar issue to https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/622

**Comment by Coeur** [comment]
For *UILabel*, according to https://www.cocoanetics.com/2015/03/customizing-uilabel-hyperlinks/ you have no way to customize the attributes of a link. The workaround is to subclass UILabel with a lot of complex changes. You can give a try to https://github.com/Krelborn/KILabel.

For *UITextView*, the link color is controlled by the tintColor property.

For *NSTextView*, the link color is controller by the linkTextAttributes property.

**Comment by Coeur** [comment]
@kusmi I will provide a small workaround. But my guess is that you are not supporting clickable links anyway?

**Comment by Coeur** [comment]
@kusmi, please give a try to version 2.1.0 and parameter skipLinkAttribute.
