### ISSUE TITLE
Naming question for new classes

### ISSUE THREAD

**Issue by Coeur** [laptobbe/TSMarkdownParser#48]
For next major version, many pre-built parsers will be available. Which names would be best, @laptobbe ?

* TSStandardParser, TSGithubParser, TSStackOverflowParser, ...
* TSMStandardParser, TSMGithubParser, TSMStackOverflowParser, ...
* TSMarkdownStandardParser, TSMarkdownGithubParser, TSMarkdownStackOverflowParser, ...

**Comment by laptobbe** [comment]
@Coeur I think the full verbose versions are the best, since you most likely will have the name autocompleted anyway.

**Comment by Coeur** [comment]
Good.
