### ISSUE TITLE
Parsing is extremely fragile? 

### ISSUE THREAD

**Issue by adamdahan** [laptobbe/TSMarkdownParser#51]
I have a little snippet for you to test and I am curious to know if you have any insights about why the parsing breaks down so easily before I go in and try to fix it up. 

This markdown below should render a simple while loop 

            ``\nwhile (YES) {\n    printf(\"Help, I am stuck in an infinite loop!\\n\");\n}\n``

But it does not render using your parser. Interestingly enough though this does: 

           `` while (YES) { \n printf(\"Help, I am stuck in an infinite loop! \\n\"); } ``

I found that the initial newline and the last two newline chars are breaking it. 

Any ideas?

**Comment by Coeur** [comment]
Hello @adamdahan, and thanks for raising the issue.

I built the regex myself in an attempt to be compatible with Character Escaping. See #46 for what was the problem, and https://github.com/laptobbe/TSMarkdownParser/commit/437d9a98b1d908cc4bfbca734a7de3adf4680509#diff-842045870396c3236b1fad63acfe6264R140 for the solution (```@"(?<!\\\\)(?:\\\\\\\\)*+(`+)(.*?[^`].*?)(\\1)(?!`)";```).

In [branch 3.x](https://github.com/laptobbe/TSMarkdownParser/blob/3.x/TSMarkdownParser/TSMarkdownParser.m), the regex is now ``@"(?<!\\\\)(?:\\\\\\\\)*+"`` concatenated with ``@"(%@+)(.*?[^%@].*?)(\\1)(?!%@)"`` where `%@` is replaced with ```.

I'll look into the issue, but feel free to provide a pull request.

**Comment by Coeur** [comment]
Maybe changing `options:(NSRegularExpressionOptions)0` to `options:NSRegularExpressionDotMatchesLineSeparators` is enough.
