### ISSUE TITLE
tvOS broken due to unavailable font

### ISSUE THREAD

**Issue by invliD** [laptobbe/TSMarkdownParser#52]
Commit da3aea3 introduced a bug that prevents TSMarkdownParser from working on tvOS. The font "Georgia-Italic", or Georgia in general, is not available, so tvOS apps crash when instantiating a `TSMarkdownParser`.

Specifically, `[UIFont fontWithName:]` returns `nil`, but `nil` cannot be the value in an `NSDictionary`.

**Comment by Coeur** [comment]
Ah, sorry about that.
Will fix it tonight.

**Comment by Coeur** [comment]
Any preference to replace Georgia? (note: the System font here is the one for iOS 9)
![available alternative fonts for Georgia](https://cloud.githubusercontent.com/assets/839992/15718636/028e26e8-285f-11e6-9487-f55ea8445f0c.png)

**Comment by invliD** [comment]
I think System would be fine.

**Comment by Coeur** [comment]
I'll go with italicSystemFont for quotes.
But Menlo isn't available for watchOS also...
